# Generated by Django 5.2.3 on 2025-07-01 13:40

from datetime import date, timedelta
from django.db import migrations, models


def set_default_winners_reveal_date(apps, schema_editor):
    SiteParameters = apps.get_model("common", "SiteParameters")
    default_date = date.today() + timedelta(days=30)
    site_parameters, _ = SiteParameters.objects.get_or_create(pk=1)
    site_parameters.winners_reveal_date = default_date
    site_parameters.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winners_reveal_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(set_default_winners_reveal_date),
    ]
