# Generated by Django 5.2.3 on 2025-07-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteparameters",
            options={
                "verbose_name": "Site Parameters",
                "verbose_name_plural": "Site Parameters",
            },
        ),
    ]
