# Generated by Django 5.2.3 on 2025-09-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_siteparameters_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteparameters',
            options={'verbose_name_plural': 'Site Parameters'},
        ),
    ]
