# Generated by Django 5.2.3 on 2025-09-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='nationality',
            new_name='nationalities',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='slug',
        ),
    ]
